# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01085f7710eb26d642a97806e5abece45dec9ea54378b5554fa2906ed495aeb56e2d4a8d0ecdee765c76e0ee2e169efbca5c3a3c4cc271b0ae2a343f0cb9afdf

test:
  secret_key_base: 8062bd5be50aaa4fae76e2da6266ef95017ada2567ac32b1151176a58c24ac744c33544a571a57ffe1f274eb89f70584954a4f330e4eacb28b3ded8d55731271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
